{% set name = "ipyaladin" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyaladin-{{ version }}.tar.gz
  sha256: 06252d685c211ccada6ebee8c6b793d9a29ef6503e0a90fd2159e86f9d75c3b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-jupyter-builder >=0.5.0
    - pip
  run:
    - python >=3.8
    - anywidget
    - astropy

test:
  imports:
    - ipyaladin
  commands:
    - pip check
  requires:
    - pip

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  home: https://github.com/cds-astro/ipyaladin
  summary: ipyaladin
  description: ipyaladin, a Jupyter widget for Aladin Lite, the sky viewer
  doc_url: https://cds-astro.github.io/ipyaladin/
  dev_url: https://github.com/cds-astro/ipyaladin

extra:
  recipe-maintainers:
    - bmatthieu3
    - tboch
