{% set name = "ipyaladin" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyaladin-{{ version }}.tar.gz
  sha256: eee74cb71bb6ff3b20f5dbf323bcbbaf69bf0b7c352bf523d29dc4533e6393a8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder >=0.5.0
    - pip
  run:
    - python >={{ python_min }}
    - anywidget
    - astropy
    - astroquery

test:
  imports:
    - ipyaladin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  home: https://github.com/cds-astro/ipyaladin
  summary: ipyaladin
  description: ipyaladin, a Jupyter widget for Aladin Lite, the sky viewer
  doc_url: https://cds-astro.github.io/ipyaladin/
  dev_url: https://github.com/cds-astro/ipyaladin

extra:
  recipe-maintainers:
    - bmatthieu3
    - tboch
